version: "3.9"
services:
  db:
    container_name: postgres
    image: postgres:15.1
    environment:
      POSTGRES_DB: goapi
      POSTGRES_USER: sing
      POSTGRES_PASSWORD: 12345678
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  api:
    container_name: go-api
    image: ghcr.io/sing3demons/devops-go:c9d81b2300d81778ee24f9835fef6f7e58875368
    build: .
    restart: always
    ports:
      - 2565:2565
    environment:
      PORT: 2565
      DB_CONNECTION: "host=db port=5432 user=sing password=12345678 dbname=goapi sslmode=disable"
    depends_on:
      - db
