apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-devops
  namespace: go-devops
spec:
  selector:
    matchLabels:
      app: go-devops
  template:
    metadata:
      labels:
        app: go-devops
    spec:
      containers:
        - name: go-devops
          image: sing3demons/devopsgo:1.0
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 2565
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 4
            failureThreshold: 4
          livenessProbe:
            exec:
              command:
                - cat
                - /tmp/live
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 30
            failureThreshold: 5
          ports:
            - containerPort: 2565
          env:
            - name: PORT
              value: "2565"
